[package]
name = "serve"
version = "0.1.0"
edition = "2021"
descirption="static serve powered by rust"
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
